stages:
  - test

test:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - flake8
    - coverage run -m pytest
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
